version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_USER: admin
      POSTGRES_DB: ceps
    volumes:
      - ./data:/data/postgres
    ports:
      - "5432:5432"
  app:
    image: cep_api
    ports:
      - 3000:3000